language: java
sudo: required
jdk:
- oraclejdk8
services:
  - postgresql
before_install:
  - psql -c "create user ilya with password 'qwerty123';" -U postgres
  - psql -c "create database ilyadb;" -U postgres
  - psql -c "grant all on database ilyadb to ilya;" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: $key
  app: apoj
  on:
    repo: java-park-mail-ru/Apoj-09-2017
    branch: develop
  skip_cleanup: true
install:
  - mvn test -B
