CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS users (
  id       SERIAL NOT NULL PRIMARY KEY,
  login    CITEXT NOT NULL UNIQUE,
  email    CITEXT NOT NULL UNIQUE,
  password TEXT   NOT NULL,
  name     TEXT   NOT NULL
)

